title: Sreyoshi Sur
description: Computational chemistry, AI, and workflows
permalink: /blog/:year/:month/:day/:title/
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
